# Change these first
owner: olivierdelomez # Your GitHub organization or username, where this repository lives
repo: monitoring3d # The name of this repository

sites:
  - name: Dento
    url: https://dento.3dcelo.com/#/
  - name: 3Dcelo
    url: https://www.3dcelo.com
  - name: Duchesse
    url: https://duchesse-aligners.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /monitoring3d
  logoUrl: https://www.3dcelo.com/wp-content/uploads/2020/04/cropped-logo-site-3-5.png
  name: Monitoring
  #introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: "Vous rencontrez un problème avec l'un de nos services ? Contactez-nous au 01 88 46 82 50"
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
